import 'package:get/get.dart';

/// AppLocalizations - جميع نصوص الترجمة للتطبيق
/// يدعم اللغات: العربية والإنجليزية
class AppLocalizations extends Translations {
   AppLocalizations();

  @override
  Map<String, Map<String, String>> get keys => {
    'ar_SA': arSA,
    'en_US': enUS,
  };

  /// الترجمات العربية
  static const Map<String, String> arSA = {
    // ===== تصفح عام =====
    'home': 'الرئيسية',
    'calculator': 'الحاسبات',
    'search': 'البحث',
    'medicine': 'الأدوية',
    'settings': 'الإعدادات',
    'more': 'المزيد',
    'back': 'رجوع',
    'next': 'التالي',
    'confirm': 'تأكيد',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'save': 'حفظ',
    'load': 'تحميل',
    'error': 'خطأ',
    'success': 'نجح',
    'warning': 'تحذير',
    'info': 'معلومة',
    'close': 'إغلاق',
    'yes': 'نعم',
    'no': 'لا',
    'empty': 'فارغ',
    'loading': 'جاري التحميل...',
    'retry': 'إعادة المحاولة',

    // ===== الصفحة الرئيسية =====
    'welcome': 'أهلاً بك',
    'welcome_message': 'اختر ميزة للبدء',
    'quick_access': 'الوصول السريع',
    'recent_activities': 'الأنشطة الحديثة',
    'view_all': 'عرض الكل',

    // ===== الحاسبات =====
    'bmi_calculator': 'حاسبة مؤشر كتلة الجسم',
    'calculate_bmi': 'احسب مؤشر كتلة جسمك',
    'calories_calculator': 'حاسبة السعرات الحرارية',
    'calculate_calories': 'احسب احتياجاتك من السعرات',
    'perfect_weight': 'الوزن المثالي',
    'calculate_ideal_weight': 'احسب وزنك المثالي بناءً على طولك',
    'blood_pressure': 'ضغط الدم',
    'check_bp_classification': 'تحقق من تصنيف ضغط دمك',
    'water_need': 'احتياج المياه',
    'calculate_daily_water': 'احسب احتياجك اليومي من المياه',
    'fat_eating': 'استهلاك الدهون',
    'daily_fat_limit': 'حد الدهون اليومي',
    'smoking_cost': 'تكلفة التدخين',
    'financial_impact_tracker': 'تتبع التأثير المالي لعادة التدخين',
    'height': 'الطول (سم)',
    'weight': 'الوزن (كجم)',
    'age': 'العمر (سنة)',
    'gender': 'الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'calculate': 'احسب',
    'result': 'النتيجة',
    'underweight': 'نقص وزن',
    'normal': 'وزن عادي',
    'overweight': 'زيادة وزن',
    'obese': 'سمنة',
    'low': 'منخفض',
    'normal_pressure': 'ضغط عادي',
    'high': 'مرتفع',
    'your_bmi': 'مؤشر كتلة جسمك',
    'your_perfect_weight': 'وزنك المثالي',
    'bp_status': 'حالة ضغط الدم',
    'daily_water_need': 'احتياجك اليومي من المياه',
    'monthly_smoking_cost': 'تكلفة التدخين الشهرية',
    'kg': 'كيلوجرام',
    'grams': 'جرام',
    'liters': 'لتر',
    'enter_valid_height': 'يرجى إدخال طول صحيح',
    'enter_valid_age': 'يرجى إدخال عمر صحيح',
    'enter_valid_number': 'أدخل رقماً صحيحاً',
    'enter_systolic': 'أدخل الضغط الانقباضي',
    'enter_diastolic': 'أدخل الضغط الانبساطي',
    'enter_valid_values': 'يرجى إدخال قيم صحيحة',
    'activity_level': 'مستوى النشاط',
    'activity_sedentary': 'قليل جداً (عمل مكتبي)',
    'activity_light': 'خفيف (رياضة 1-3 أيام)',
    'activity_moderate': 'متوسط (رياضة 3-5 أيام)',
    'activity_high': 'مكثف (رياضة 6-7 أيام)',
    'cigs_per_day': 'عدد السجائر يومياً',
    'cigs_per_pack': 'عدد السجائر في العلبة',
    'cost_per_pack': 'سعر العلبة',
    'enter_cigs_per_day': 'أدخل عدد السجائر يومياً',
    'enter_cigs_per_pack': 'أدخل عدد السجائر في العلبة',
    'enter_cost_per_pack': 'أدخل سعر العلبة',

    // ===== البحث والدردشة =====
    'search_questions': 'ابحث عن الأسئلة',
    'ask_question': 'اسأل سؤالاً',
    'common_questions': 'الأسئلة الشائعة',
    'chat': 'محادثة',
    'send': 'إرسال',
    'message': 'رسالة',
    'reply': 'رد',
    'no_results': 'لا توجد نتائج',
    'search_hint': 'ابحث هنا...',

    // ===== الأدوية والتذكيرات =====
    'medicine_reminder': 'تذكر الأدوية',
    'add_medicine': 'إضافة دواء',
    'medicine_name': 'اسم الدواء',
    'enter_medicine_name': 'أدخل اسم الدواء',
    'fill_medicine_details': 'املأ تفاصيل الدواء',
    'basic_info': 'المعلومات الأساسية',
    'medicine_settings': 'إعدادات الدواء',
    'dosage': 'الجرعة',
    'dosage_unit': 'وحدة الجرعة',
    'frequency': 'التكرار',
    'start_date': 'تاريخ البداية',
    'end_date': 'تاريخ النهاية',
    'time': 'الوقت',
    'times': 'الأوقات',
    'notes': 'ملاحظات',
    'once_daily': 'مرة واحدة يومياً',
    'twice_daily': 'مرتان يومياً',
    'thrice_daily': 'ثلاث مرات يومياً',
    'weekly': 'أسبوعياً',
    'monthly': 'شهرياً',
    'daily': 'يومياً',
    'pill': 'حبة',
    'tablet': 'قرص',
    'capsule': 'كبسولة',
    'liquid': 'سائل',
    'injection': 'حقنة',
    'medicine_added_success': 'تمت إضافة الدواء بنجاح',
    'medicine_deleted': 'تم حذف الدواء',
    'medicine_updated': 'تم تحديث الدواء',
    'take_medicine': 'تناول الدواء',
    'medicine_taken': 'تم تناول الدواء',
    'skip': 'تخطي',
    'remind_me_later': 'ذكرني لاحقاً',

    // ===== النموذج والحقول =====
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'full_name': 'الاسم الكامل',
    'first_name': 'الاسم الأول',
    'last_name': 'الاسم الأخير',
    'phone': 'رقم الهاتف',
    'address': 'العنوان',
    'city': 'المدينة',
    'country': 'الدول',
    'required_field': 'هذا الحقل مطلوب',
    'invalid_email': 'البريد الإلكتروني غير صحيح',
    'password_mismatch': 'كلمات المرور غير متطابقة',
    'weak_password': 'كلمة المرور ضعيفة',

    // ===== الرسائل والإخطارات =====
    'no_internet': 'لا توجد اتصال بالإنترنت',
    'connection_restored': 'تم استعادة الاتصال',
    'operation_failed': 'فشلت العملية',
    'try_again': 'حاول مرة أخرى',
    'something_went_wrong': 'حدث خطأ ما',
    'invalid_input': 'إدخال غير صحيح',
    'please_fill_all_fields': 'يرجى ملء جميع الحقول',
    'data_saved': 'تم حفظ البيانات',
    'data_deleted': 'تم حذف البيانات',
    'are_you_sure': 'هل أنت متأكد؟',
    'confirm_delete': 'هل تريد حذف هذا العنصر؟',
    'confirm_action': 'هل تريد المتابعة؟',

    // ===== إعدادات التطبيق =====
    'language': 'اللغة',
    'theme': 'المظهر',
    'notifications': 'الإخطارات',
    'enable_notifications': 'تفعيل الإخطارات',
    'sound': 'الصوت',
    'vibration': 'الاهتزاز',
    'about': 'حول التطبيق',
    'version': 'الإصدار',
    'privacy': 'سياسة الخصوصية',
    'terms': 'شروط الاستخدام',
    'contact_us': 'اتصل بنا',
    'logout': 'تسجيل الخروج',
    'account': 'الحساب',
    'profile': 'الملف الشخصي',
    'data_and_privacy': 'البيانات والخصوصية',
    'help': 'المساعدة',

    // ===== Main View & Navigation =====
    'the_news_of_healthy': 'أخبار الصحة',
    'quick_links': 'الروابط السريعة',
    'features': 'الميزات',
    'splash_welcome': 'أهلاً وسهلاً بك في BetterMe',
    'splash_description': 'تطبيقك الصحي الشامل',

    // ===== Calculator Specific =====
    'enter_height': 'أدخل طولك',
    'enter_weight': 'أدخل وزنك',
    'enter_age': 'أدخل عمرك',
    'select_gender': 'اختر جنسك',
    'bmi_status': 'حالة مؤشر كتلة الجسم',
    'calories_daily': 'السعرات الحرارية اليومية',
    'water_liters': 'الكمية بالليترات',
    'systolic': 'الضغط الانقباضي',
    'diastolic': 'الضغط الانبساطي',
    'cost_per_day': 'التكلفة يومياً',
    'cost_per_month': 'التكلفة شهرياً',
    'cost_per_year': 'التكلفة سنوياً',

    // ===== Search & Chat =====
    'ask_healthcare_question': 'اسأل سؤالاً صحياً',
    'type_message': 'اكتب رسالتك...',
    'no_messages': 'لا توجد رسائل بعد',
    'searching': 'جاري البحث...',
    'error_loading': 'حدث خطأ في التحميل',
    'common_faqs': 'الأسئلة الشائعة',
    'search_faq': 'ابحث في الأسئلة الشائعة',
    'find_answers_quickly': 'اعثر على الإجابات بسرعة',
    'search_placeholder_faq': 'ابحث عن سؤالك...',
    'ask_ai_question': 'اسأل الذكاء الاصطناعي',
    'what_do_you_want_to_know': 'ماذا تريد أن تعرف؟',
    'ask_health_questions': 'اسأل أسئلتك الصحية',
    'thank_you_for_asking': 'شكراً لك على السؤال. نحن نحاول جاهدين للعثور على أفضل إجابة لك. يرجى الانتظار قليلاً.',
    'similar_questions': 'أسئلة مشابهة',
    'no_similar_questions': 'لا توجد أسئلة مشابهة',
    'search_no_results': 'لم نجد أي نتائج للبحث',
    'try_different_keywords': 'حاول البحث بكلمات مختلفة',
    'search_results': 'نتائج البحث',
    'result_count': 'عدد النتائج',
    'clear_search': 'مسح البحث',
    'popular_questions': 'الأسئلة الشائعة',
    'tap_to_see_answers': 'اضغط لعرض الإجابات',
    'loading_faqs': 'جاري تحميل الأسئلة الشائعة',
    'start_asking': 'ابدأ بطرح الأسئلة',
    'ask_anything_health': 'اسأل عن أي شيء متعلق بصحتك',
    'searching_answer': 'جاري البحث عن الإجابة...',
    'answer_found': 'تم العثور على الإجابة',
    'retry_action': 'حاول مرة أخرى',

    // ===== Medicine & Medicine Reminder =====
    'medicine_list': 'قائمة الأدوية',
    'my_medicines': 'أدويتي',
    'daily_dose': 'الجرعة اليومية',
    'no_medicines': 'لا توجد أدوية مضافة',
    'start_adding': 'ابدأ بإضافة أول دواء',
    'add_first_medicine': 'أضف أول دواء لتتبعه',
    'take_medicine_reminder': 'تنبيه: حان وقت تناول الدواء',
    'medicine_time': 'وقت الدواء',
    'medicine_dosage': 'جرعة الدواء',
    'medicine_type': 'نوع الدواء',
    'medicine_frequency': 'عدد مرات التناول',
    'set_reminder': 'ضبط التذكير',
    'reminder_set': 'تم ضبط التذكير بنجاح',
    'type': 'النوع',
    'status': 'الحالة',
    'taken': 'تم تناوله',
    'missed': 'لم يتم تناوله',
    'pending': 'قيد الانتظار',
    'every_hour': 'كل ساعة',
    'every_hours': 'كل {{count}} ساعات',
    'medicine_added': 'تم إضافة الدواء بنجاح',
    'confirm_delete_medicine': 'هل تريد حذف {{medicine}}؟',
    'edit_medicine': 'تعديل الدواء',
    'delete_medicine': 'حذف الدواء',
    'view_details': 'عرض التفاصيل',
    'syrup': 'شراب',
    'cream': 'كريم',
    'mark_as_taken': 'وضّع كمأخوذ',
    'medicine_instruction': 'تعليمات التناول',
    'medicine_notes': 'ملاحظات إضافية',
    'start_date_medicine': 'تاريخ البداية',
    'end_date_medicine': 'تاريخ الانتهاء',
    'no_end_date': 'بدون تاريخ انتهاء',
    'next_dose': 'الجرعة القادمة',
    'last_taken': 'آخر مرة تم تناوله',
    'today': 'اليوم',
    'tomorrow': 'غداً',
    'times_per_day': 'مرات في اليوم',
    'next_reminder': 'التذكير القادم',
    'set_time': 'اختر الوقت',
    'starting_time': 'وقت البداية',
    'select_time': 'اختر الوقت',
    'remind_me_every': 'ذكرني كل',
    'select_interval': 'اختر الفترة الزمنية',
    'hours': 'ساعات',
    'type_bottle': 'زجاجة',
    'type_pill': 'حبة',
    'type_syringe': 'حقنة',
    'type_tablet': 'قرص',
    'update': 'تحديث',
    'error_medicine_name_required': 'يرجى إدخال اسم الدواء',
    'error_medicine_exists': 'هذا الدواء موجود بالفعل',
    'error_dosage_invalid': 'الجرعة غير صحيحة',
    'error_interval_required': 'يرجى اختيار الفترة الزمنية',
    'error_start_time_required': 'يرجى اختيار وقت البداية',
    'medicine_updated_successfully': 'تم تحديث الدواء بنجاح',
    'take_medicine_reminder_default': 'حان وقت تناول الدواء حسب الجدول',
    'error_loading_medicines': 'خطأ في تحميل الأدوية',
    'error_adding_medicine': 'خطأ في إضافة الدواء',
    'error_updating_medicine': 'خطأ في تحديث الدواء',
    'error_deleting_medicine': 'خطأ في حذف الدواء',
    'error_saving_medicines': 'خطأ في حفظ الأدوية',
    'medicine_added_successfully': 'تمت إضافة الدواء بنجاح',
    'medicine_deleted_successfully': 'تم حذف الدواء بنجاح',
    'reminder': 'تنبيه',

    // ===== Common UI Elements =====
    'no_data': 'لا توجد بيانات',
    'refresh': 'تحديث',
    'done': 'تم',
    'cancel_action': 'إلغاء',
    'search_placeholder': 'ابحث...',
    'no_match': 'لا توجد نتائج متطابقة',
    'loading_data': 'جاري تحميل البيانات...',
    'dismiss': 'إغلاق',
    'ok': 'حسناً',
    'action_not_allowed': 'هذا الإجراء غير مسموح به',
    'permission_denied': 'تم رفض الإذن',
    'network_error': 'خطأ في الشبكة',
    'timeout': 'انتهت مهلة الاتصال',

    // ===== Home Page Enhancements =====
    'good_morning': 'صباح الخير 🌅',
    'good_afternoon': 'مساء الخير ☀️',
    'good_evening': 'تمساء الخير 🌙',
    'trending': 'الآن',
    'health_tips': 'نصائح صحية مهمة',
    'expert_tips': 'نصائح خبراء',
    'health_recommendations': 'التوصيات الصحية',
    'tap_to_learn_more': 'اضغط لمزيد',

    // ===== FAQ Questions =====
    'faq_q1': 'ما هي أهمية الحمية الصحية؟',
    'faq_q2': 'ما هي الأدوية المستخدمة لعلاج نزلات البرد؟',
    'faq_q3': 'ما هي الأمراض الشائعة في فصل الشتاء؟',
    'faq_q4': 'هل يمكن استخدام الأدوية المضادة للالتهابات بدون وصفة طبية؟',
    'faq_q5': 'هل يمكن الوقاية من الأمراض المعدية عن طريق التطعيم؟',
    'faq_q6': 'ما هي أهمية النوم الجيد في صحتنا؟',
    'faq_q7': 'هل يؤثر التوتر النفسي على الصحة؟',
    'faq_q8': 'ما هي أهمية ممارسة التمارين الرياضية بانتظام؟',

    // ===== FAQ Answers =====
    'faq_a1': 'الحمية الصحية تلعب دورًا هامًا في المحافظة على الصحة والوقاية من الأمراض.',
    'faq_a2': 'يمكن استخدام الأدوية المسكنة لتخفيف أعراض نزلات البرد مثل الصداع والحمى.',
    'faq_a3': 'بعض الأمراض الشائعة في فصل الشتاء تشمل الإنفلونزا ونزلات البرد والتهاب الحلق.',
    'faq_a4': 'تعتبر الأدوية المضادة للالتهابات من الأدوية الموصوفة عادةً، ويجب استشارة الطبيب قبل استخدامها.',
    'faq_a5': 'نعم، التطعيم يعتبر وسيلة فعالة للوقاية من الأمراض المعدية.',
    'faq_a6': 'النوم الجيد يلعب دورًا هامًا في تجديد الجسم واستعادة الطاقة وتعزيز الصحة العامة.',
    'faq_a7': 'نعم، التوتر النفسي المستمر قد يؤدي إلى مشاكل صحية مثل ارتفاع ضغط الدم وأمراض القلب.',
    'faq_a8': 'ممارسة التمارين الرياضية بانتظام تساهم في تحسين اللياقة البدنية والقوة والمرونة والتوازن.',
  };

  /// الترجمات الإنجليزية
  static const Map<String, String> enUS = {
    // ===== General Navigation =====
    'home': 'Home',
    'calculator': 'Calculators',
    'search': 'Search',
    'medicine': 'Medicine',
    'settings': 'Settings',
    'more': 'More',
    'back': 'Back',
    'next': 'Next',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'save': 'Save',
    'load': 'Load',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'close': 'Close',
    'yes': 'Yes',
    'no': 'No',
    'empty': 'Empty',
    'loading': 'Loading...',
    'retry': 'Retry',

    // ===== Home Page =====
    'welcome': 'Welcome',
    'welcome_message': 'Select a feature to get started',
    'quick_access': 'Quick Access',
    'recent_activities': 'Recent Activities',
    'view_all': 'View All',

    // ===== Calculators =====
    'bmi_calculator': 'BMI Calculator',
    'calculate_bmi': 'Calculate your Body Mass Index',
    'calories_calculator': 'Calories Calculator',
    'calculate_calories': 'Calculate your daily calorie needs',
    'perfect_weight': 'Perfect Weight',
    'calculate_ideal_weight': 'Calculate your ideal weight based on height',
    'blood_pressure': 'Blood Pressure',
    'check_bp_classification': 'Check your blood pressure classification',
    'water_need': 'Water Need',
    'calculate_daily_water': 'Calculate your daily water requirement',
    'fat_eating': 'Fat Eating',
    'daily_fat_limit': 'Daily Fat Limit',
    'smoking_cost': 'Smoking Cost',
    'financial_impact_tracker': 'Track the financial impact of smoking',
    'height': 'Height (cm)',
    'weight': 'Weight (kg)',
    'age': 'Age (years)',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'calculate': 'Calculate',
    'result': 'Result',
    'underweight': 'Underweight',
    'normal': 'Normal',
    'overweight': 'Overweight',
    'obese': 'Obese',
    'low': 'Low',
    'normal_pressure': 'Normal',
    'high': 'High',
    'your_bmi': 'Your BMI',
    'your_perfect_weight': 'Your Perfect Weight',
    'bp_status': 'Blood Pressure Status',
    'daily_water_need': 'Your Daily Water Need',
    'monthly_smoking_cost': 'Your Monthly Smoking Cost',
    'kg': 'kg',
    'grams': 'grams',
    'liters': 'liters',
    'enter_valid_height': 'Please enter a valid height',
    'enter_valid_age': 'Please enter a valid age',
    'enter_valid_number': 'Please enter a valid number',
    'enter_systolic': 'Enter systolic pressure',
    'enter_diastolic': 'Enter diastolic pressure',
    'enter_valid_values': 'Please enter valid values',
    'activity_level': 'Activity Level',
    'activity_sedentary': 'Sedentary (office work)',
    'activity_light': 'Light (1-3 days exercise)',
    'activity_moderate': 'Moderate (3-5 days exercise)',
    'activity_high': 'Intense (6-7 days exercise)',
    'cigs_per_day': 'Cigarettes per day',
    'cigs_per_pack': 'Cigarettes per pack',
    'cost_per_pack': 'Cost per pack',
    'enter_cigs_per_day': 'Enter daily cigarettes',
    'enter_cigs_per_pack': 'Enter cigarettes per pack',
    'enter_cost_per_pack': 'Enter cost per pack',

    // ===== Search & Chat =====
    'search_questions': 'Search Questions',
    'ask_question': 'Ask a Question',
    'common_questions': 'Common Questions',
    'chat': 'Chat',
    'send': 'Send',
    'message': 'Message',
    'reply': 'Reply',
    'no_results': 'No Results Found',
    'search_hint': 'Search here...',

    // ===== Medicine & Reminders =====
    'medicine_reminder': 'Medicine Reminder',
    'add_medicine': 'Add Medicine',
    'medicine_name': 'Medicine Name',
    'enter_medicine_name': 'Enter medicine name',
    'fill_medicine_details': 'Fill medicine details',
    'basic_info': 'Basic Information',
    'medicine_settings': 'Medicine Settings',
    'dosage': 'Dosage',
    'dosage_unit': 'Dosage Unit',
    'frequency': 'Frequency',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'time': 'Time',
    'times': 'Times',
    'notes': 'Notes',
    'once_daily': 'Once Daily',
    'twice_daily': 'Twice Daily',
    'thrice_daily': 'Thrice Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'daily': 'Daily',
    'pill': 'Pill',
    'tablet': 'Tablet',
    'capsule': 'Capsule',
    'liquid': 'Liquid',
    'injection': 'Injection',
    'medicine_added_success': 'Medicine Added Successfully',
    'medicine_deleted': 'Medicine Deleted',
    'medicine_updated': 'Medicine Updated',
    'take_medicine': 'Take Medicine',
    'medicine_taken': 'Medicine Taken',
    'skip': 'Skip',
    'remind_me_later': 'Remind Me Later',

    // ===== Forms & Fields =====
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'full_name': 'Full Name',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'phone': 'Phone',
    'address': 'Address',
    'city': 'City',
    'country': 'Country',
    'required_field': 'This field is required',
    'invalid_email': 'Invalid email address',
    'password_mismatch': 'Passwords do not match',
    'weak_password': 'Password is too weak',

    // ===== Messages & Notifications =====
    'no_internet': 'No Internet Connection',
    'connection_restored': 'Connection Restored',
    'operation_failed': 'Operation Failed',
    'try_again': 'Try Again',
    'something_went_wrong': 'Something Went Wrong',
    'invalid_input': 'Invalid Input',
    'please_fill_all_fields': 'Please fill all fields',
    'data_saved': 'Data Saved',
    'data_deleted': 'Data Deleted',
    'are_you_sure': 'Are you sure?',
    'confirm_delete': 'Are you sure you want to delete this item?',
    'confirm_action': 'Do you want to continue?',

    // ===== App Settings =====
    'language': 'Language',
    'theme': 'Theme',
    'notifications': 'Notifications',
    'enable_notifications': 'Enable Notifications',
    'sound': 'Sound',
    'vibration': 'Vibration',
    'about': 'About App',
    'version': 'Version',
    'privacy': 'Privacy Policy',
    'terms': 'Terms of Use',
    'contact_us': 'Contact Us',
    'logout': 'Logout',
    'account': 'Account',
    'profile': 'Profile',
    'data_and_privacy': 'Data & Privacy',
    'help': 'Help',

    // ===== Main View & Navigation =====
    'the_news_of_healthy': 'Health News',
    'quick_links': 'Quick Links',
    'features': 'Features',
    'splash_welcome': 'Welcome to BetterMe',
    'splash_description': 'Your Comprehensive Health App',

    // ===== Calculator Specific =====
    'enter_height': 'Enter your height',
    'enter_weight': 'Enter your weight',
    'enter_age': 'Enter your age',
    'select_gender': 'Select your gender',
    'bmi_status': 'BMI Status',
    'calories_daily': 'Daily Calories',
    'water_liters': 'Amount in Liters',
    'systolic': 'Systolic Pressure',
    'diastolic': 'Diastolic Pressure',
    'cost_per_day': 'Cost per Day',
    'cost_per_month': 'Cost per Month',
    'cost_per_year': 'Cost per Year',

    // ===== Search & Chat =====
    'ask_healthcare_question': 'Ask a Health Question',
    'type_message': 'Type your message...',
    'no_messages': 'No messages yet',
    'searching': 'Searching...',
    'error_loading': 'Error loading',
    'common_faqs': 'Common FAQs',
    'search_faq': 'Search in FAQs',
    'find_answers_quickly': 'Find answers quickly',
    'search_placeholder_faq': 'Search for your question...',
    'ask_ai_question': 'Ask AI',
    'what_do_you_want_to_know': 'What do you want to know?',
    'ask_health_questions': 'Ask your health questions',
    'thank_you_for_asking': 'Thank you for asking. We are trying hard to find the best answer for you. Please wait a moment.',
    'similar_questions': 'Similar Questions',
    'no_similar_questions': 'No similar questions',
    'search_no_results': 'No results found for your search',
    'try_different_keywords': 'Try searching with different keywords',
    'search_results': 'Search Results',
    'result_count': 'Results Count',
    'clear_search': 'Clear Search',
    'popular_questions': 'Popular Questions',
    'tap_to_see_answers': 'Tap to see answers',
    'loading_faqs': 'Loading FAQs',
    'start_asking': 'Start asking',
    'ask_anything_health': 'Ask anything about your health',
    'searching_answer': 'Searching for answer...',
    'answer_found': 'Answer found',
    'retry_action': 'Try again',

    // ===== Medicine & Medicine Reminder =====
    'medicine_list': 'Medicine List',
    'my_medicines': 'My Medicines',
    'daily_dose': 'Daily Dose',
    'no_medicines': 'No medicines added',
    'start_adding': 'Start adding your first medicine',
    'add_first_medicine': 'Add your first medicine to track',
    'take_medicine_reminder': 'Reminder: Time to take medicine',
    'medicine_time': 'Medicine Time',
    'medicine_dosage': 'Medicine Dosage',
    'medicine_type': 'Medicine Type',
    'medicine_frequency': 'Frequency',
    'set_reminder': 'Set Reminder',
    'reminder_set': 'Reminder set successfully',
    'type': 'Type',
    'status': 'Status',
    'taken': 'Taken',
    'missed': 'Missed',
    'pending': 'Pending',
    'every_hour': 'Every hour',
    'every_hours': 'Every {{count}} hours',
    'medicine_added': 'Medicine added successfully',
    'confirm_delete_medicine': 'Are you sure you want to delete {{medicine}}?',
    'edit_medicine': 'Edit Medicine',
    'delete_medicine': 'Delete Medicine',
    'view_details': 'View Details',
    'syrup': 'Syrup',
    'cream': 'Cream',
    'mark_as_taken': 'Mark as Taken',
    'medicine_instruction': 'Instructions',
    'medicine_notes': 'Additional Notes',
    'start_date_medicine': 'Start Date',
    'end_date_medicine': 'End Date',
    'no_end_date': 'No End Date',
    'next_dose': 'Next Dose',
    'last_taken': 'Last Taken',
    'today': 'Today',
    'tomorrow': 'Tomorrow',
    'times_per_day': 'Times per Day',
    'next_reminder': 'Next Reminder',
    'set_time': 'Set Time',
    'starting_time': 'Starting Time',
    'select_time': 'Select Time',
    'remind_me_every': 'Remind me every',
    'select_interval': 'Select Interval',
    'hours': 'hours',
    'type_bottle': 'Bottle',
    'type_pill': 'Pill',
    'type_syringe': 'Syringe',
    'type_tablet': 'Tablet',
    'update': 'Update',
    'error_medicine_name_required': 'Please enter medicine name',
    'error_medicine_exists': 'This medicine already exists',
    'error_dosage_invalid': 'Invalid dosage',
    'error_interval_required': 'Please select reminder interval',
    'error_start_time_required': 'Please select starting time',
    'medicine_updated_successfully': 'Medicine updated successfully',
    'take_medicine_reminder_default': 'Time to take your medicine according to schedule',
    'error_loading_medicines': 'Error loading medicines',
    'error_adding_medicine': 'Error adding medicine',
    'error_updating_medicine': 'Error updating medicine',
    'error_deleting_medicine': 'Error deleting medicine',
    'error_saving_medicines': 'Error saving medicines',
    'medicine_added_successfully': 'Medicine added successfully',
    'medicine_deleted_successfully': 'Medicine deleted successfully',
    'reminder': 'Reminder',

    // ===== Common UI Elements =====
    'no_data': 'No Data',
    'refresh': 'Refresh',
    'done': 'Done',
    'cancel_action': 'Cancel',
    'search_placeholder': 'Search...',
    'no_match': 'No matching results',
    'loading_data': 'Loading data...',
    'dismiss': 'Dismiss',
    'ok': 'OK',
    'action_not_allowed': 'This action is not allowed',
    'permission_denied': 'Permission Denied',
    'network_error': 'Network Error',
    'timeout': 'Connection Timeout',

    // ===== Home Page Enhancements =====
    'good_morning': 'Good Morning 🌅',
    'good_afternoon': 'Good Afternoon ☀️',
    'good_evening': 'Good Evening 🌙',
    'trending': 'Trending Now',
    'health_tips': 'Important Health Tips',
    'expert_tips': 'Expert Tips',
    'health_recommendations': 'Health Recommendations',
    'tap_to_learn_more': 'Tap to learn more',

    // ===== FAQ Questions =====
    'faq_q1': 'What is the importance of a healthy diet?',
    'faq_q2': 'What medicines are used to treat colds?',
    'faq_q3': 'What are common winter diseases?',
    'faq_q4': 'Can anti-inflammatory drugs be used without a prescription?',
    'faq_q5': 'Can infectious diseases be prevented by vaccination?',
    'faq_q6': 'What is the importance of good sleep in our health?',
    'faq_q7': 'Does psychological stress affect health?',
    'faq_q8': 'What is the importance of regular exercise?',

    // ===== FAQ Answers =====
    'faq_a1': 'A healthy diet plays an important role in maintaining health and preventing diseases.',
    'faq_a2': 'Painkillers can be used to relieve cold symptoms such as headaches and fever.',
    'faq_a3': 'Some common winter diseases include flu, colds, and sore throat.',
    'faq_a4': 'Anti-inflammatory drugs are usually prescribed medications, and you should consult a doctor before using them.',
    'faq_a5': 'Yes, vaccination is an effective way to prevent infectious diseases.',
    'faq_a6': 'Good sleep plays an important role in renewing the body, restoring energy, and promoting overall health.',
    'faq_a7': 'Yes, continuous psychological stress can lead to health problems such as high blood pressure and heart disease.',
    'faq_a8': 'Regular exercise helps improve physical fitness, strength, flexibility, and balance.',
  };
}
